### ISSUE TITLE
Customize meta (Twitter/etc) copy

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#17]
Sometimes the DEK isn't ideal for the meta description tag; can we add an optional field to specify it manually?

**Comment by misfist** [comment]
Do you mean an SEO description field?

**Comment by frnsys** [comment]
The part that shows under the title like here:

![image](https://cloud.githubusercontent.com/assets/1059947/25637379/ca5eb728-2f52-11e7-9797-50d1f4994f92.png)

**Comment by frnsys** [comment]
Hey @misfist has this been deployed to production?

**Comment by misfist** [comment]
Yes, it's now deployed on production. There is a field called "SEO Description".

**Comment by frnsys** [comment]
Oh I see it now, thanks!
