### ISSUE TITLE
Contributors page empty?

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#27]
I can't figure out what's different between production and staging, but on production https://thenewinquiry.com/contributors/ is empty, but on staging (http://tni-staging.positiondevapp.com/contributors) the contributors are listing fine.

**Comment by misfist** [comment]
We haven't run the script to copy the role from users to guest authors, so they don't have assigned roles.

https://github.com/thenewinquiry/tni-core-functionality/commit/43c9d410c874a4b2ac0b7d34008b37a32c9c9578#diff-fece8c5879816a2194a875743e095a97R72

Run using WP-CLI `wp eval 'tni_core_assign_guest_author_roles();'`

**Comment by frnsys** [comment]
great, just ran it and it's all good now. thanks!

**Comment by misfist** [comment]
Cool. Please note, that users that were assigned to something other than contributor (admin, editor, etc) won't be included when `role = contributor`. So, you may want to make some adjustments to the roles assigned.

I also wanted to point out that the shortcode and template tag accept arguments.

`[guest-author-list]` accepts 2 arguments:

- `number` (number of authors to display)
- `role` (the role from which to display authors)

The template tag `tni_core_coauthors_wp_list_authors` accepts an array of arguments:

- `hide_empty` - whether or not to show authors that have no posts associated with them (default: true)
- `description` - whether or not to display the author's bio description (default: true)
- `number` - number of authors to display (default: 200)
- `role` - the role from which to display authors. If none is specified, all guest authors will be displayed (default: none) 

Lastly, if you want to change the display of the list, you can override the template within the theme. Just copy `templates/loop-authors.php` from the core plugin to the `template-parts` directory in the theme. Then, modify it.
