### ISSUE TITLE
public preview for drafts

### ISSUE THREAD

**Issue by antiboredom** [misfist/tni-core-functionality#30]
It would be nice if there was an easy way to show drafts of posts to people who aren't logged in. I found a plugin that does this - wondering what you guys think?

https://wordpress.org/plugins/public-post-preview/

**Comment by misfist** [comment]
It may be possible to handle this another way. Could you please explain the use case for this?

**Comment by antiboredom** [comment]
Sure - the use case is getting feedback on posts from people who don't have accounts.

**Comment by antiboredom** [comment]
(By the way this is totally not essential or anything - just an idea!)
