### ISSUE TITLE
warnings on local installation

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#33]
I'm moving from a vagrant local setup to a docker-based one (my computer can't really handle a full VM well).

so far everything seems ok, except for two warnings:

>  Warning: Missing argument 2 for TNI_Core_Authorization::__construct(), called in /var/www/html/wp-content/plugins/tni-core-functionality/includes/authorization-functions.php on line 43 and defined in /var/www/html/wp-content/plugins/tni-core-functionality/includes/class-tni-core-authorization.php on line 75

>  Warning: Missing argument 3 for tni_toggle_auth_menu_items() in /var/www/html/wp-content/themes/tni/inc/extras.php on line 175

any idea why these would be happening?

not a huge issue but thought maybe the answer might be obvious!

**Comment by misfist** [comment]
It's caused by the `TNI_Core_Authorization` class being instantiated without passing required values: `$file` and `$version`. I'll update to pass a default $version, so it won't be required.

**Comment by frnsys** [comment]
perfect, thanks!
