### ISSUE TITLE
Checkbox for manually toggling subscriber-only status?

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#38]
Can we add an additional checkbox for subscriber-only status in addition to the subscriber-only date we currently have? Such that it only becomes public if the box is unchecked, even if we pass the subscriber-only date (essentially, we have to manually toggle it to be public). 

So a post is public if-and-only-if the checkbox is unchecked (which is the default), regardless of the subscriber-only date.

**Comment by misfist** [comment]
This has been added and merged.

**Comment by frnsys** [comment]
working great, thank you!
