### ISSUE TITLE
Updating the plugin on staging

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#7]
hey @misfist, what's the best way of updating this on the staging server? The trellis system doesn't seem to take care of it.

**Comment by misfist** [comment]
There is a deploy script. I can take care of that a bit later. 

On April 16, 2017 1:22:28 PM EDT, Francis Tseng <notifications@github.com> wrote:
>hey @misfist, what's the best way of updating this on the staging
>server? The trellis system doesn't seem to take care of it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thenewinquiry/tni-core-functionality/issues/7

~/Pea

**Comment by frnsys** [comment]
Ok thanks - I just manually updated it for now
