### ISSUE TITLE
Deploy updated plugin?

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#9]
hey Pea,

I updated the plugin to version 1.0.12 in `composer.json` but I'm not seeing my updates on the staging server after deploying them. Is there something else I need to do before those changes will be pulled?

**Comment by misfist** [comment]
There is no 1.0.12 tag in the repo. Versions need to be tagged in order for composer to be able to download them.

**Comment by frnsys** [comment]
I just tagged it and deployed to staging, but still doesn't seem like my changes took.

**Comment by frnsys** [comment]
Also I updated  & tagged the theme but am having a similar issue.

**Comment by misfist** [comment]
Yes, I've been having similar issues intermittently, but am not sure why. I managed to get it updated to the latest versions by running again.

**Comment by misfist** [comment]
@emhoracek - this is the same deployment issue I was reporting. Updates to our theme and plugin (and sometimes other packages) aren't implemented on the server during deployment.

**Comment by emhoracek** [comment]
@misfist Thanks for tagging me. I'm on vacation this week but I'll try to research how exactly Ansible works -- with any luck, once I really understand that, I'll be able to look at our workflow and the configs and it'll be obvious what's going on. :crossed_fingers: 🍀

**Comment by frnsys** [comment]
I think I might have figured out what's going on. It seems that trellis doesn't run `composer update`...when I go into the server and run `composer update` in `/srv/www/thenewinquiry.com/current`, the plugin updates. Not sure why this isn't just part of the playbook :\

**Comment by misfist** [comment]
Yes, I found the same thing.

**Comment by misfist** [comment]
I had no problems today updating 3-rd party plugins and WordPress core on staging today. What I did was run `composer update` locally, then pushed `composer.json` and `composer.lock` to the repo. Then, I ran the deployment script.

**Comment by frnsys** [comment]
Ok great - so then I should setup my vagrant environment to use Trellis as well. I'll close this now
